### ISSUE TITLE
Running locally gives error on localhost:8000, but works at localhost:3000.

### ISSUE THREAD

**Issue by ya332** [cfranklin11/docker-django-react#7]
I get this error when I do `docker-compose up` and go to localhost:8000 in production-heroku branch

![image](https://user-images.githubusercontent.com/26026196/65610939-16a17a00-df80-11e9-831e-089e886356b5.png)
The error is that index.html doesn't exist at /.

Code:
production-heroku

Error:
index.html not found at /

Steps to reproduce:
`docker-compose build`
`docker-compose up`
Then go to localhost:8000 in your web browser

Thanks,
Yigit

**Comment by cfranklin11** [comment]
A little late, but I'm just seeing this now. The frontend is all served via the Webpack server on port 3000. The Django app is just an API that the frontend consumes, so it doesn't serve any frontend assets. If you're seeing a functioning page on port 3000, then it's working as intended.

**Comment by ya332** [comment]
Got it thanks! I can confirm this is the solution.
